ln -s user-home.png deepin-user-home.png
ln -s user-home.png folder-home.png
ln -s user-home.png folder_home.png
ln -s user-home.png user-home-symbolic.png
ln -s folder-download.png folder-downloads.png 
ln -s folder-download.png folder-download-symbolic.png 
ln -s folder-recent.png folder-recent-symbolic.png
ln -s folder-videos.png folder-videos-symbolic.png
ln -s folder-music.png folder-music-symbolic.png
ln -s user-trash.png user-trash-full.png
ln -s user-trash.png user-trash-full-symbolic.png
ln -s folder.png folder-symbolic.png
